name: CI

on:
  push:
    branches:
      - main
  

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Deps
        run: |
          npm ci

      - name: Format
        run: |
          npm run format 
      - name: Lint
        run: |
          npm run lint
          npm run format:check

      - name: Test
        run: |
          npm run test:ci

      - name: Build
        run: |
          npm run build
          cp package.json dist/
          
      - name: run build
        run: npm run build 
      
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: result
          path: dist/

